Tas interface commands
MortenTobiasNielsen/Factorio-GUI-V2 pull request #226
Opened 2023-03-28 08:20 UTC by theis999

Added the TAS console commands to the interface, allowing other mods to use them.
Which is useful for my TAS helper, as i can create buttons that execute the commands.

Control.lua scrips of "Theis TAS helper" where it is used:
[control.zip](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/files/11086984/control.zip)

Note: this is built on #215 to prevent merge conflicts

2023-03-31 14:59 UTC, MortenTobiasNielsen requested changes

2023-03-31 14:59 UTC, MortenTobiasNielsen commented on src/GenerateScript.cpp
> +		<< tab << tab << "timestamp = \"" << currentDateTime() << "\"" << comma_endl
I would like to use std::chrono::system_clock::now(); unless you really need the very specific date format made in the currentDateTime function.

2023-03-31 14:59 UTC, MortenTobiasNielsen commented on src/GenerateScript.cpp
> +	this->name = folder_location.substr(folder_location.find_last_of('\\') + 1);
Is this used for anything?

2023-03-31 16:25 UTC, theis999 commented on src/GenerateScript.cpp
> +	this->name = folder_location.substr(folder_location.find_last_of('\\') + 1);
It is used exactly once, in the method GenerateScript::ClearSteps() line 50.

2023-04-02 05:45 UTC, theis999 commented on src/GenerateScript.cpp
> +		<< tab << tab << "timestamp = \"" << currentDateTime() << "\"" << comma_endl
Done

2023-04-02 06:53 UTC, MortenTobiasNielsen approved these changes

2023-04-02 06:53 UTC, merged