Step Modifiers
MortenTobiasNielsen/Factorio-GUI-V2 pull request #258
Opened 2023-04-25 11:34 UTC by theis999

### Step modifiers changes how a single step is interpreted
This is either in the Generator or in the TAS execution.

There are included 4 modifiers:
1. No order
2. Wait for
3. Cancel
4. Walk towards

**Wait for** and **cancel others** are fairly simple.
### No order
Is only applied to a small subset of action types, it also isn't very performant. So ideally the user will apply it while developing and then change the order of their commands to match the execution.

#### It works by
Setting up a step block to execute, by iterating from the current step and forwards until it finds a step that isn't "no order"
Then it runs through each step every tick.
If a step is executed, it will then be removed from the step block
When the step block is empty, it returns to normal operations.

#### Notes
Every executed step will print a debug message, so you can see the order they are executed in.
If the execution of the step block exceeds 25 times the number of steps, it will fail. This might be low?
To suppress warnings generated by steps that can't be executed, the warning function is overwritten while block is being executed.

### Walk towards
Can be used to generate a walk step where the direction matters more than the destination. It means that the TAS will proceed with the next walk step once every step in between has been executed.
This however does mean that the generator, loses the ability to know where the character is.

I have added the walk towards modifier on intermediate steps. As it made sense to me that for these steps the user doesn't care about the location of the character. This is however **not backwards compatible**, so it might not be a great idea?

2023-04-25 13:13 UTC, MortenTobiasNielsen commented
The GUI isn't scaled correctly and can be a little difficult to see what modifiers are on a step. 
![image](https://user-images.githubusercontent.com/48355480/234287421-a27045cc-5ca3-43c5-bf5c-a93f01eae658.png)

2023-04-25 22:46 UTC, theis999 commented
I restyled it so it fits better.
Added the usual double click functionality
And added click handler similar to the painter to "no order" so it's possible to change multiple steps.

I don't know how to display the potentially very long modifier strings, other than this.

2023-05-05 06:33 UTC, MortenTobiasNielsen requested changes

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on src/ImportStepsPanel.cpp
> +		step.Buildings = segments[8] != "" ? stoi(segments[8]) : 1;
This seems to be inconsistent. Why do _direction_ need to check that the size is >= 6 when _Size_ doesn't?

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +
I want to be able to specify an amount which should be finished in the assembler. I know I can go back and change what I put into the assembler, that can sometimes be 20-40 assemblers. It is therefore easier to just specify what you want finished in there, so you don't have to go back.

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +
Won't this consume a tick instead of adding and cancelling in the same tick? Will it consume multiple ticks?

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +	msg(string.format("Research: %s %s added", item, not was_addded and "not"))
I find this pretty hard to read - how does it behave?

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +		if _success then
You can put doStep(_step) directly into the if statement, so you don't have to allocate memory for _success - it might be optimized away, but I am not sure whether LUA does that.

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +		elseif(steps[step][2] == "walk" and ( walking.walking == false or global.walk_towards_state) and idle < 1) then
Remove the space in front of walking.walking

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +		elseif steps[step][2] ~= "walk" and steps[step][2] ~= "idle" and steps[step][2] ~= "mine" then
Why did you change the order of idle and mine?

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	auto& m = gridEntry->Modifiers;
Change m to modifiers

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	string m = "";
Change m to modifiers

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	stepParameters.Modifiers = m.substr(0, m.size() > 2 ? m.size() - 2 : m.size());
I think this would be easier to read if it was:
```
stepParameters.Modifiers = modifiers.size < 2 ? "" : substr(0, m.size() - 2 );
```

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	}
It seems like this behavior could be confusing to the user - if I read it correctly. Won't it make it so that the behavior will depend on whether all the steps marked can have the "No Order" modifier, but it doesn't tell me that I am not able to do that with the currently selected steps. 

I think it would give a better user experience if "No Order" was disabled if the user has selected a set of steps which makes it impossible to use "No Order" or it only mark the steps which can get the modifier.

2023-05-05 06:33 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +					step.Modifiers.substr(0, size - 8);
You should specify these _magic numbers_ (10 and 8)

2023-05-08 06:00 UTC, theis999 commented on src/ImportStepsPanel.cpp
> +		step.Buildings = segments[8] != "" ? stoi(segments[8]) : 1;
Fair point, i do think it is the later parts like _Size_ that should follow.

2023-05-08 06:11 UTC, theis999 commented on Lua Files/control.lua
> +
Yes, that is the idea. That it follows the rule that actions cost ticks. So it cost 1 tick per research to remove, however since dependent techs will be cancelled too.

2023-05-08 07:08 UTC, theis999 commented on Lua Files/control.lua
> +
I am uncertain how best to add such a value. As the _Amount_ field is already used (or abused). I can see 3 options:
1. Move the auto-fill amount to the auto-fill panel. Which opens the amount field for set recipe.
2. Add a Wait-for amount somewhere in the modifier panel. 
3. Change wait-for to only block when recipe progress is < 90%.

2023-05-08 07:15 UTC, theis999 commented on Lua Files/control.lua
> +		if _success then
I doubt LUA does much of anything _smart_, it is a very small language. Performance-wise I don't think it matters either way, but it is slightly easier to step through with a debugger this way.

2023-05-08 07:18 UTC, theis999 commented on Lua Files/control.lua
> +		elseif steps[step][2] ~= "walk" and steps[step][2] ~= "idle" and steps[step][2] ~= "mine" then
Not sure. I moved lots of lines around so it might just have been an accident.

2023-05-08 07:22 UTC, theis999 commented on src/cMain.cpp
> +					step.Modifiers.substr(0, size - 8);
Correct!

2023-05-08 07:32 UTC, theis999 commented on src/cMain.cpp
> +	}
The UX of using no-order needs a lot more work. Getting everything to work with just one button is tricky. Some your idea might be useful.

2023-05-08 07:56 UTC, theis999 commented on Lua Files/control.lua
> +	msg(string.format("Research: %s %s added", item, not was_addded and "not"))
Now the code is wrong, and should have been: 
`msg(string.format("Research: %s%s added", item, not was_addded and " not" or ""))`

It is the same as `!was_added ? " not" : ""`

2023-05-11 08:58 UTC, theis999 commented on Lua Files/control.lua
> +	msg(string.format("Research: %s %s added", item, not was_addded and "not"))
I have made the fix mentioned.

2023-05-11 09:00 UTC, theis999 commented on src/cMain.cpp
> +	}
I have updated this, so it both colours the no-order checkbox indicating special behavior, and provides a warning telling the user if a step can't be updated this way.

2023-05-11 09:07 UTC, theis999 commented
I have made several changes based on the comments.

Everything but one issue should be resolved now. The last one being wait-for, where i have requested input.

2023-05-15 17:21 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +		if _success then
Fair point - it most likely won't make a difference, so if it makes it easier to debug it probably worth it.

2023-05-15 17:52 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +
I think we should do option 2 and put it into the modifier field. This way we don't introduce a breaking change by moving/changing the "meaning" of amount

2023-05-15 17:53 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +
I guess that makes sense, but it is also a breaking change. I guess it isn't a problem as long as the possibility to use the "Cancel" comment  is still there.

2023-05-15 18:10 UTC, MortenTobiasNielsen requested changes
I have found these things when I was trying out the new functionality. 
Small typo in the msg box - should be "unable to **be** assigned"
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/cfa237a1-6d25-4b39-bd83-9a9ba0c949e6)

These is not enough space in the left panel, which means that a horizontal scroll bar is added when the vertical scroll bar is added:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/24368151-5e69-4d50-b430-a20ee11ce3c2)

After playing around with the No order modifier I have somehow gotten it into a state where it keeps being red even though I should be able to add the modifier to the selected steps:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/3221df67-4332-4da4-ad63-eb165d259c71)

In this bugged state it seems to disables all modifier if only one step is selected:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/12768bf0-59e6-4a83-bdcb-0b78b98c9782)

When I selected build it stopped being disabled, but it seems to think that one or multiple of the selected steps have the No order modifier and doesn't seem to be aware that the game speed cannot get the No order modifier:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/67aeb025-54f7-4368-adab-5ae45088f332)

It would be nice to have some sort of explanation as to what blue and red means. Red somewhat makes sense - but why isn't it disabled if I cannot click it? I don't really understand blue - does it just indicate that more than one step has been selected?

It seems like the movement color indicators haven't been moved:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/ed3aa414-0d81-41cf-af35-29985f849585)

I find it pretty difficult to try out every possible combination of the modifiers, but I hope I have found most of what isn't working as intended.

2023-05-15 18:10 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +		elseif steps[step][2] ~= "walk" and steps[step][2] ~= "idle" and steps[step][2] ~= "mine" then
Can you change it back - now that we any way need to make some changes? I am sure that it doesn't mean anything, but I don't really like changes without any meaning. :)

2023-05-15 18:14 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +	msg(string.format("Research: %s%s added", item, not was_addded and " not" or ""))
I still don't know how to read this. Can you write this instead if it provides the same result? It makes it so much easier to read for people which isn't neck deep in LUA code. :D
```
msg(string.format("Research: %s%s added", item, was_addded ? "" : " not"))
```

2023-05-15 20:20 UTC, theis999 commented on Lua Files/control.lua
> +
Added it as separate issue

2023-05-15 20:30 UTC, theis999 commented on Lua Files/control.lua
> +	msg(string.format("Research: %s%s added", item, not was_addded and " not" or ""))
Sure! that is cleaner.

2023-05-15 20:52 UTC, theis999 commented on Lua Files/control.lua
> +	msg(string.format("Research: %s%s added", item, not was_addded and " not" or ""))
Lua doesn't have `?` operator but we can use `and` to mimic the behavior.
But the order of conditions are important as the last item is the one returned.
So ``` "" and was_added or " not" ``` would result in `false` or `" not"`.

2023-05-15 21:21 UTC, theis999 commented
I corrected the **typo** and reversed the **order of operators** for **tech** was added to simplify the expression.

Unfortunately I can't see the issue with the **scrollbars**. I was very careful with placing it **pixel perfect**. Maybe we have different monitor resolutions? anyway, as i can't see the issue you have and i want to use the full space. The easiest solution is for you to make the necessary adjustment.

#### No-order
It seems to me that the colouring of the no-order checkbox has you more confused. Which is a shame because it means that i have replaced one UI problem with another.

Anyway, it has 4 states.
1. Disabled - The current step-**type** doesn't allow no-order
2. Enabled (black) - The current step-**type** allows no-order
3. Blue - You have selected multiple rows **and** the current step-**type** allows no-order
4. Red - You have selected multiple rows **and** the current step-**type** doesn't allow no-order

In other words the colouring of the checkbox indicates whether the change will affect the step you currently designing in the top row, and has nothing to do with the selected steps in the step panel being able to be changed.

Whether the multiple steps selected can be changed is handled, when you try, using the warning box.

2023-05-16 04:15 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +	msg(string.format("Research: %s%s added", item, not was_addded and " not" or ""))
Sad that it isn't possible, but sure lets go with that.

2023-05-16 05:28 UTC, MortenTobiasNielsen commented
Yeah that is really confusing - borderline misleading. I do understand that it is pretty much impossible to convey all of the information necessary  with just one checkbox and some colors, but it is almost better with no colors, in that case it at least doesn't give visual ques which can be interpreted wrong. 

Maybe we can have a No Order and a No Order Row or something like that, so it is clear that one affects the row and the other the current step?

2023-05-16 08:44 UTC, theis999 commented on Lua Files/control.lua
> +	msg(string.format("Research: %s%s added", item, not was_addded and " not" or ""))
Yeah it is a bit sad with Lua's limitations but at least it isn't Udon.

2023-05-16 11:06 UTC, theis999 commented
It sounds to me as if you see it as a button that looks like checkbox, while it is in fact a checkbox that also has a button like behavior. So when the checkbox changes color it indicates (1) that it has button-like behavior and (2) the color indicates whether it retains checkbox-like behavior, with red by no and blue being yes. 

Maybe an more intuitive solution is to use a button for the button-type behavior. The button could be placed at the same location as the checkbox - toggling between visibility of the two control elements based on how many rows the user selects.

I would find it highly misleading if it just gave the modifier to any step that is able to have it. As it would create 2 step blocks even though the user selected a continues block of rows. It would be fine for something like `Ctrl+click`, but the current setup can't detect that.

2023-05-16 17:38 UTC, MortenTobiasNielsen commented
Agreed - a button would be better. Sounds like a good idea to have it as a ctrl-click.

2023-05-17 05:40 UTC, theis999 commented
I have swapped the logic to use a button instead of only relying on the checkbox.
The button looks slightly weird, as i had make it slightly shorter than standard to fit in checkbox grid layout.

I added a right click handler that doesn't give warnings.

2023-05-17 18:06 UTC, MortenTobiasNielsen approved these changes
Lets give it a try. :D

2023-05-17 18:06 UTC, merged