Undo and Redo
MortenTobiasNielsen/Factorio-GUI-V2 pull request #272
Opened 2023-05-15 11:14 UTC by theis999

This adds the option to Ctrl+Z to undo and Ctrl+Y to redo a few types of actions.

It is built State modifiers, so there are some unrelated commits included.

The change can be broken into 4 categories:
1. Undo and Redo has been added to the shortcut menu
2. Command stack, class has been added
3. Undo and Redo handlers has been added the can reverse the user actions
4. The clickhandlers for the commands have been modified to fit into the undo and redo handlers

### Command stack
The command stack is a custom circular buffer that can handle 32 elements. In such a way that overflow overrides old elements. However it is also possible to pop items of the stack (REDO) and further it is possible to pop_back items (UNDO) reusing the items on it.

### Not included
This only observes ADD, DELETE, CHANGE, MOVE UP, and MOVE DOWN for the steps grid.
Which means MOVE 5, import steps, colouring, no-order modifier, everything template, etc. Is not included.

2023-05-19 06:06 UTC, MortenTobiasNielsen requested changes
I wanted to test out the new functionality and tried to delete 3 random rows and press undo, but for some reason it 4 rows comes back. 
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/ed34512a-4ed7-44a1-b8d6-45de6fe47ead)
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/8c03eb02-0c7b-48f4-b54c-c7180abdaf94)
Not really sure why that would happen, it isn’t duplicating one of the rows. I thought for a second it might have taken row 10707 for some reason, but the coordinates are not the same.

I cannot seem to find the change, but it seems like the Save (file) shortcut has been overridden:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/ef6ac7a3-efbf-4da7-9994-dd635ab3d12a)

I have this setup for testing:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/c5e9aaac-53c8-4e10-aebf-f2d62c87f06a)
I first added the build step and then added the mine steps from 1 to 10 and then I deleted the build step. When I undo and redo multiple times, I sometimes get this: 
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/e6af1705-c404-483b-a0ad-8ac45cf1ce38)
Where it seems like the tool thinks that it is mining the inserter even though it has not been built. It is not consequent about which row gets it. 
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/d58b2d80-25a6-4f64-9f16-94217f5a9a7b)

I changed 4 to 100 and 7 to 200 and then undid the changes, but for some reason 7 turned into 6. It did though turn 4 back to 4. 
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/7a73e4a7-f175-4c45-a6a3-683c4d2b734a)

2023-05-19 06:06 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +				.row = *grid_steps->GetSelectedRows().begin() - 1,
I get this access violation error crashing the tool. It seems to be an off by 1 error where it doesn't take into account that there might not be anything in the grid:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/86d687b4-82e8-4224-8246-a97f0f20aef0)

2023-05-19 07:50 UTC, theis999 commented
Your save shortcut can be set through the shortcut changer. Ctrl+S is just the default.

2023-05-19 08:29 UTC, theis999 commented on src/cMain.cpp
> +				.row = *grid_steps->GetSelectedRows().begin() - 1,
I'll be honest i probably didn't test no-selection properly. As it is so rare to get into that state, you can use ctrl+click to get into it. 
I have fix for this issue.

2023-05-19 09:03 UTC, theis999 commented
It looks like the first issue you found is related to auto-put. As the extra step matches the recipe. So i have made a fix for it.

I can't seem to replicate the issue with mining, even though your explanation is good. Perhaps it was fixed with one of the other changes?

2023-05-19 14:49 UTC, MortenTobiasNielsen commented
True it isn't often, but would be nice if new players were able to add their first step without the tool crashing. :D

Fair point - I am just pretty sure that I haven't changed the shortcut - is it because you have changed it on the branch and it spills over to my "config"?

Well spotted. I think you are right that it is due to the recipe. It could very well be a side effect solved by one of your changes.

2023-05-19 16:48 UTC, MortenTobiasNielsen requested changes
I tried to delete all steps in my file and "undo", which crashed the tool: 
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/36cdb1f3-39cb-4738-a681-bfe892961406)

I unfortunately still get the error with the mine step thinking that it is mining something which hasn't been build yet. 
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/6f2e5beb-3dbb-4685-baa0-03670011c892)

Steps to reproduce (I hope):

1. Add build inserter step.
2. Add each of the mining steps starting with 1. 
3. Delete the Inserter step.
4. Use undo to get the inserter step back.
5. Use undo 5-6 times to remove some of the mining steps.
6. Press redo fast multiple times until all mining steps are back.

2023-05-19 16:48 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	auto steps = DeleteSteps(rows);
I can see that this is populated with data, but I have no idea why it does that, given that it doesn't seem like DeleteSteps explicitly return anything other than on line 808, which shouldn't be hit.

2023-05-19 16:48 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	for (auto& [r, _] : rows)
I would be come comfortable with for (auto& row : rows). I don't really think decomposing provides any benefit here - it might though also just be the lack of a meaningful name for "r".

2023-05-19 16:48 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +void cMain::OnRedoMenuSelected(wxCommandEvent& event)
Add a new line to separate the functions.

2023-05-20 04:35 UTC, theis999 commented on src/cMain.cpp
> +	auto steps = DeleteSteps(rows);
C++ magic apparently 🤣 I have no idea how that worked either. 
I have added a return statement at the end of DeleteSteps so it is a bit more sensible.

2023-05-20 04:38 UTC, theis999 commented on src/cMain.cpp
> +	for (auto& [r, _] : rows)
Personally i don't mind the name to much when it is used so close to it's definition. But i will change r => row.

2023-05-20 05:02 UTC, theis999 commented
I have added a stack reset on open file, as that left stack in an obviously wrong state. Which i think fixes the first issue you highlighted.
I can reproduce the other error. Correcting it may take a while.

2023-05-20 05:51 UTC, MortenTobiasNielsen requested changes
How does this resolve the "step thinks it can mine a building which haven't been build yet" problem?

2023-05-20 05:51 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	StepGridData.insert(it1, *stepParameters);
Are you sure this works? I would have guessed that I added the branch for a reason.

2023-05-20 05:51 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	for (auto& [row, _] : rows)
It is somewhat strange extracting something from the rows list isn't a row, but instead that object has a row property in it. I know it is mostly semantics, but it is somewhat confusing to read, given that it doesn't really make sense.

2023-05-20 05:51 UTC, MortenTobiasNielsen commented on src/cMain.cpp
>  	}
Add a new line.

2023-05-20 06:07 UTC, theis999 commented on src/cMain.cpp
> +	StepGridData.insert(it1, *stepParameters);
I am certain. All this did was push a row to different point in StepGridData than the grid_steps.

The branching doesn't make sense anyway. Since we already have a row to insert at. 
Overriding that row in a method this far down in the call-stack is incredibly confusing.

2023-05-20 06:12 UTC, theis999 commented on src/cMain.cpp
> +	for (auto& [row, _] : rows)
I think i can see what you mean. It is not entirely obvious what each part of the data type represent:
vector is the list of rows
tuple is a concatenation of row index and row data
StepParameters is the row data

`for (auto& [index, data] : rows)` might be more semantically correct.

2023-05-20 06:24 UTC, theis999 commented
It solves by correcting the underlying data structure StepGridData. The issue you found was just a symptom, of the gui not representing the data correctly while the real issue was that the underlying structure was updated incorrectly.

Because you deleted all steps you ended in a situation where no rows were selected in the steps grid. When redo'ing steps these steps would not exclusively be added at the end of the steps list. However as there was no selection, the redone step was added correctly in steps_grid but at the end of StepGridData.

So if you ran a generate steps you'd see that the steps were different from what was in the GUI.

2023-05-20 06:58 UTC, MortenTobiasNielsen requested changes

2023-05-20 06:58 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	for (auto& [row, _] : rows)
Agreed, that makes more sense.

2023-05-20 06:58 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	StepGridData.insert(it1, *stepParameters);
Fair point, seems like all the refactoring have made this obsolete and possibly incorrect. Just somewhat strange, that it haven't caused any problems for me, now that I have used to the tool pretty extensively.

2023-05-20 06:59 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	StepGridData.insert(it1, *stepParameters);
Fair point, seems like all the refactoring have made this obsolete and possibly incorrect. Just somewhat strange, that it haven't caused any problems for me, now that I have used to the tool pretty extensively.

2023-05-20 07:00 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	for (auto& [row, _] : rows)
Agreed, that makes more sense.

2023-05-21 06:09 UTC, theis999 commented on src/cMain.cpp
> +	StepGridData.insert(it1, *stepParameters);
It wouldn't cause any issues as long as there isn't a discrepancy between the row you interact on and the row that is selected. It is really only Undo/Redo and import-steps that would insert rows invariant of row selection.

2023-05-21 07:48 UTC, MortenTobiasNielsen approved these changes

2023-05-21 07:48 UTC, merged