Changed Goal and Log level
MortenTobiasNielsen/Factorio-GUI-V2 pull request #279
Opened 2023-05-19 12:50 UTC by theis999

Added dependency on MOD: Speedrun_goals
Added log config to control print level
Added print config for more specific printing control
Added variables.lua file to hold other generated variables 
Removed goal files as goals are now controlled by Speedrun_goals

Goals and log-level now have separate menus. Where the goal is controlled by speedrun goals.

### Speedrun goals
Speedrun goal handles rock yield and always day.

settings-updates.lua controls the settings of speedrun goals, so we can set the settings how we want them.

### Variables
The variables.lua file allows us to insert the variables we want / need without messing with control.lua or steps.lua. As both files are sufficiently large already.

### Log level
I have included 3 levels of logging. So we can reduce the amount of information printed to console more precisely.
We can easily enough introduce new levels with this setup.

In addition more specific settings are introduced to control printing of comment, research queue and save game.

2023-05-19 15:51 UTC, MortenTobiasNielsen requested changes
It would be nice if there was a little explanation of what each log level does - it is not really obvious what debug, development and release does.

2023-05-19 15:51 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +local function Message(msg)
Good idea to use message instead of msg - can you make the change to the input as well? :)

2023-05-19 15:51 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +local debug_state = LOGLEVEL < 2
Why is debug_state active when LOGLEVEL is below 2 when it needs to be LOGLEVEL == 0 for it to print a debug message? (line 130)?

2023-05-19 15:51 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +		if PRINT_SAVEGAME then debug(string.format("Step: %s, saving game as %s", task, nameOfSaveGame)) end
Why are LOGLEVEL, PRINT_SAVEGAME, etc. in all caps?

2023-05-19 15:51 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +local function Comment(msg)
Good idea to add a Comment function - cleans up the code nicely.

2023-05-19 15:51 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> -
I am not sure I like this idea that the tool is so tightly coupled with an external tool.

2023-05-19 15:51 UTC, MortenTobiasNielsen commented on Lua Files/settings-updates.lua
> +    ["t-sg-sand-rock-big-stone"] = {type = "int-setting", value = 24},--[19 : 25]
I very much don't like this idea - I think we have talked about it at a few times.

2023-05-21 06:26 UTC, theis999 commented on Lua Files/control.lua
> +local function Message(msg)
Done

2023-05-21 06:38 UTC, theis999 commented on Lua Files/control.lua
> +local debug_state = LOGLEVEL < 2
This might have been a stupid decision from me.
Previous we had 2 configurations debug and not_debug, while it is obvious that the new "Release" configuration match not_debug. It is however not obvious if debug matches the new "Debug" or "Development".

The best approach might be to just straight up remove debug_state entirely?

2023-05-21 06:44 UTC, theis999 commented on Lua Files/control.lua
> +		if PRINT_SAVEGAME then debug(string.format("Step: %s, saving game as %s", task, nameOfSaveGame)) end
It was meant to indicate that they are global variables. But it does follow the Lua style for constants.

2023-05-21 06:58 UTC, theis999 commented on Lua Files/control.lua
> -
You do have mod privilegies so you can ensure that it is up to standard.
For release of a TAS the supporting mod is automatically downloaded & enabled, and for development it should be fairly easy for most people to ensure it is enabled.

Is there any job you would be fine with having a supporting mod take care of?

2023-05-21 07:06 UTC, theis999 commented
It is a bit annoying that the help doesn't show up for log-levels as i did actually type it out.
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/18309265/589f93d3-400d-4743-b509-502b7798e308)

**Speedrun Goals**
One of my projects for this mod is to create a custom GUI for winning the game. Which includes the total time taken for beating the game in milliseconds and time to research technologies instead of kills
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/18309265/9791e9c1-f80f-4ca9-a8a2-8128d7ecd56d)
As this is likely to include several lines of code to create, i want it far away from the rest of the TAS handling.

2023-05-21 07:57 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> +local debug_state = LOGLEVEL < 2
I guess LOGLEVEL could be used instead. So when debug_state should be false we set the LOGLEVEL to 3?

2023-05-21 08:26 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> -
I appreciate that I have mod privileges, but I would still like this tool to be able to function without the user having to "remember" that a mod is needed for it to function. 

I think the idea of having a nice GUI for the winning condition makes a lot of sense and will enhance the use experience, and it doesn't need to be a part of the FTG tool, so it is a good idea to externalize it, like the other semi-support tools.

2023-05-21 08:28 UTC, MortenTobiasNielsen commented
Strange that the help message isn't shown, but seems to be an issue with the framework, so nothing really to do about it other than crossing fingers that it will be solved at some point. 

Sounds like a nice mod, which will be useful for many players. I did though think that speed runners aren't allowed to use mods, so will they be able to use this?

2023-05-22 11:35 UTC, theis999 commented on Lua Files/control.lua
> +local debug_state = LOGLEVEL < 2
I have revamped debug_state so it is exclusive to compatibility mode.

2023-05-22 11:37 UTC, theis999 commented on Lua Files/control.lua
> -
It is not exactly something you can forget. As the TAS mod simply won't load without the dependency being enabled too.

2023-05-22 11:54 UTC, theis999 commented on Lua Files/settings-updates.lua
> +    ["t-sg-sand-rock-big-stone"] = {type = "int-setting", value = 24},--[19 : 25]
I've removed the reliance on Speedrun goals' rock handling.
So it is only handles ending the game.

2023-05-22 12:00 UTC, theis999 commented
> ...I did though think that speed runners aren't allowed to use mods, so will they be able to use this?

They do, so they won't. But that doesn't particularly matter to me :)

I've changed the integration with the mod, so it only handles the endgame trigger and displaying the endgame gui.
I have removed most uses of debug_state.
I have added a new Error method, which should only be used for fatal errors.

2023-05-22 17:27 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> -
Fair, but it really is nicer that it just works, instead of it telling me that it doesn't work because I don't have a "third-party" mod installed.

2023-05-22 17:39 UTC, MortenTobiasNielsen commented
When I generate script with this branch my run doesn't work at all. It seems to just be something with it needing a dependency, but I would really appreciate it if that wasn't the case. I do not think the dependency provides enough value for it to warrant a breaking change.

2023-05-24 06:00 UTC, theis999 commented on Lua Files/control.lua
> -
I am not going to pretend i understand the issue you have. If the developer distribute their TAS through the mod portal dependencies are automatically download & enabled. If the developer have created other TAS's then they should know what to do. If the developer switch between different TAS mods, the mod will automatically be enabled. When is this an issue?

Seeing that the mod is not loaded is simple enough:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/18309265/26ad5c7f-c724-4605-a84d-12cfeff0b615)

2023-05-24 06:08 UTC, theis999 commented
I have run my steel axe TAS using this branch, and it worked perfectly fine. Providing me with End game GUI that i previously had to hack in.

2023-05-27 07:11 UTC, MortenTobiasNielsen commented on Lua Files/control.lua
> -
How would the developer know that they suddenly have to install a mod to make it work - it haven't been needed before? I am aware that it is easy to do - like it is easy to download an extension, but I still would still like for a tool to at least function without external things. 

Why is it so important to tightly couple the goal tool instead of emitting an event like we do with other things?

2023-06-02 10:08 UTC, theis999 commented
I'll close this PR and reopen a new one to keep it more focus as a lot have changed.

2023-06-02 10:08 UTC, closed without merging