Split shortcut menu into shortcuts and step types
MortenTobiasNielsen/Factorio-GUI-V2 pull request #282
Opened 2023-05-22 06:31 UTC by theis999

- Added new menu Step types
- Moved step types shortcuts to new menu.
- Added step types shortcuts for those that were missing. 
- Added new shortcut to select the search field.
- Added right click handlers to change step and delete step. 
- Added shortcut that match right click handlers of buttons. 
- Added new page in shortcut changer to handle the new menu.
- Added tooltips to buttons Step panels that didn't have them
- Fixed search columns, oversight with modifiers.

![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/18309265/6a3bd7b4-a9f2-4fa8-8bb8-96970f4beb10)
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/18309265/c835ccec-468a-4f0c-9d2d-c0acd8d1f758)
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/18309265/a3190e86-e40e-4774-9533-dcfbc7ca4238)
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/18309265/c258f308-5346-401f-906a-386ab033eafb)

2023-05-22 17:56 UTC, MortenTobiasNielsen requested changes
It seems like a good amount of the step types are still in the shortcuts tab:
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/3a9a80cd-8fc0-4559-b555-e4e8cf38ecaf)

2023-05-22 17:56 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +	no_changes = false;
There is a lot of copy paste here from OnDeleteStepClicked - can you consolidate it a little?

2023-05-22 17:56 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +
There is a lot of copy paste here from OnChangeStepClicked - can you consolidate it a little?

2023-05-22 20:24 UTC, theis999 commented on src/cMain.cpp
> +	no_changes = false;
I can try at least.

2023-05-23 04:48 UTC, theis999 commented on src/cMain.cpp
> +	no_changes = false;
Done

2023-05-23 04:48 UTC, theis999 commented on src/cMain.cpp
> +
Done

2023-05-23 07:47 UTC, theis999 commented
The issue you are seeing is essentially a migration issue. That should be fixed now.

2023-05-25 20:47 UTC, theis999 commented on src/cMain.cpp
> +		OnChangeStepClicked(event);
This appears to wrong

2023-05-27 07:16 UTC, MortenTobiasNielsen commented on src/cMain.cpp
> +		OnChangeStepClicked(event);
I what way?

2023-05-27 07:18 UTC, MortenTobiasNielsen commented
I am not able to build the branch. I have tried to delete it locally and pull it again, but it didn't solve the problem.
![image](https://github.com/MortenTobiasNielsen/Factorio-TAS-Generator/assets/48355480/f8dec45c-c0d3-4e6b-8c04-38cfb99bb823)

2023-05-27 15:22 UTC, theis999 commented on src/cMain.cpp
> +		OnChangeStepClicked(event);
It should use the right click method. Otherwise the key bind won't work properly.

2023-05-27 15:34 UTC, theis999 commented
It is appears to have been a migration issue. Leaving in 2 function declarations. They should be fixed now, sorry. I won't use github's merge tool again.

2023-06-04 06:40 UTC, MortenTobiasNielsen approved these changes

2023-06-04 06:40 UTC, merged